CREATE DATABASE plataformaTEA;
USE plataformaTEA;
CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
    fecha_registro DATETIME DEFAULT CURRENT_TIMESTAMP
);
